# Generated by Django 5.1.2 on 2024-10-30 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_opened', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_ticket', to='social.ticket')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='social_tick_created_85b7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketreply',
            index=models.Index(fields=['-responded_at'], name='social_tick_respond_e8ec61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketreply',
            unique_together={('ticket', 'reply')},
        ),
    ]
