# Generated by Django 5.1.2 on 2024-11-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_post_saved_by_ticket_ticketreply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['responded_at']},
        ),
        migrations.RemoveIndex(
            model_name='ticketreply',
            name='social_tick_respond_e8ec61_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticketreply',
            index=models.Index(fields=['responded_at'], name='social_tick_respond_f09a62_idx'),
        ),
    ]
